- name: functions
  hosts: local
  connection: local
  vars:
    persons: "naresh,veeranala,kumar"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: naresh
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict  }}"


  - name: convert to uppercase
    vars:
      name: "Naresh veeranala"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to uppercase
    vars:
      name: "Naresh veeranala"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}""