- name: functions
  hosts: local
  connection: local
  vars:
    persons: "naresh,veeranala,kumar"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: naresh
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"